/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package alphav1

import (
	"context"
	"time"

	scheme "github.com/AlexsJones/k8s-workload-metadata-provider/apis/client/clientset/versioned/scheme"
	alphav1 "github.com/AlexsJones/k8s-workload-metadata-provider/apis/metadata/alphav1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// MetaDataContextTypesGetter has a method to return a MetaDataContextTypeInterface.
// A group's client should implement this interface.
type MetaDataContextTypesGetter interface {
	MetaDataContextTypes(namespace string) MetaDataContextTypeInterface
}

// MetaDataContextTypeInterface has methods to work with MetaDataContextType resources.
type MetaDataContextTypeInterface interface {
	Create(ctx context.Context, metaDataContextType *alphav1.MetaDataContextType, opts v1.CreateOptions) (*alphav1.MetaDataContextType, error)
	Update(ctx context.Context, metaDataContextType *alphav1.MetaDataContextType, opts v1.UpdateOptions) (*alphav1.MetaDataContextType, error)
	UpdateStatus(ctx context.Context, metaDataContextType *alphav1.MetaDataContextType, opts v1.UpdateOptions) (*alphav1.MetaDataContextType, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*alphav1.MetaDataContextType, error)
	List(ctx context.Context, opts v1.ListOptions) (*alphav1.MetaDataContextTypeList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *alphav1.MetaDataContextType, err error)
	MetaDataContextTypeExpansion
}

// metaDataContextTypes implements MetaDataContextTypeInterface
type metaDataContextTypes struct {
	client rest.Interface
	ns     string
}

// newMetaDataContextTypes returns a MetaDataContextTypes
func newMetaDataContextTypes(c *MetadataAlphav1Client, namespace string) *metaDataContextTypes {
	return &metaDataContextTypes{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the metaDataContextType, and returns the corresponding metaDataContextType object, and an error if there is any.
func (c *metaDataContextTypes) Get(ctx context.Context, name string, options v1.GetOptions) (result *alphav1.MetaDataContextType, err error) {
	result = &alphav1.MetaDataContextType{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("metadatacontexttypes").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of MetaDataContextTypes that match those selectors.
func (c *metaDataContextTypes) List(ctx context.Context, opts v1.ListOptions) (result *alphav1.MetaDataContextTypeList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &alphav1.MetaDataContextTypeList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("metadatacontexttypes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested metaDataContextTypes.
func (c *metaDataContextTypes) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("metadatacontexttypes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a metaDataContextType and creates it.  Returns the server's representation of the metaDataContextType, and an error, if there is any.
func (c *metaDataContextTypes) Create(ctx context.Context, metaDataContextType *alphav1.MetaDataContextType, opts v1.CreateOptions) (result *alphav1.MetaDataContextType, err error) {
	result = &alphav1.MetaDataContextType{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("metadatacontexttypes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(metaDataContextType).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a metaDataContextType and updates it. Returns the server's representation of the metaDataContextType, and an error, if there is any.
func (c *metaDataContextTypes) Update(ctx context.Context, metaDataContextType *alphav1.MetaDataContextType, opts v1.UpdateOptions) (result *alphav1.MetaDataContextType, err error) {
	result = &alphav1.MetaDataContextType{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("metadatacontexttypes").
		Name(metaDataContextType.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(metaDataContextType).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *metaDataContextTypes) UpdateStatus(ctx context.Context, metaDataContextType *alphav1.MetaDataContextType, opts v1.UpdateOptions) (result *alphav1.MetaDataContextType, err error) {
	result = &alphav1.MetaDataContextType{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("metadatacontexttypes").
		Name(metaDataContextType.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(metaDataContextType).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the metaDataContextType and deletes it. Returns an error if one occurs.
func (c *metaDataContextTypes) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("metadatacontexttypes").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *metaDataContextTypes) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("metadatacontexttypes").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched metaDataContextType.
func (c *metaDataContextTypes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *alphav1.MetaDataContextType, err error) {
	result = &alphav1.MetaDataContextType{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("metadatacontexttypes").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
